package net.fbridault.gmwolf.gmstruct.generator.ir;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Path;

/**
 * Represents a game maker script
 * Created by felix on 01/07/2017.
 */
public class Script {
    String name;
    String desc;
    StringBuilder body;
    StringBuilder parameters;

    public Script(String name, String desc) {
        this.name = name;
        this.desc = desc.equals("") ? "///@desc " + desc : "";
        this.body = new StringBuilder();
        parameters = new StringBuilder();
    }

    public Script append(Object o) {
        body.append(o);
        return this;
    }

    public String getName() {
        return name;
    }

    public String getBody() {
        return body.toString();
    }

    @Override
    public String toString() {
        return desc + "\n" + parameters.toString() + "\n" + body.toString();
    }

    public void addParameter(String name, String desc) {
        parameters.append("///@param ").append(name).append(" ").append(desc).append("\n");
    }

    public void write(Path path) throws IOException {
        Path p = path.resolve(name+".gml");
        File file = p.toFile();

        file.getParentFile().mkdir();
        if (!file.exists()) {
            file.createNewFile();
        }

        PrintWriter writer = new PrintWriter(file, "UTF-8");
        writer.println("///Generated by GMStruct");
        writer.print(this);
        writer.close();
    }
}
